import {StyleSheet} from 'react-native';
import {colors, metrics, scale, typography, verticalScale} from 'src/theme';

export const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: metrics.padding.md,
    borderBottomWidth: 1,
    borderBottomColor: '#e6e6e6',
    backgroundColor: '#FFFFFF',
    height: verticalScale(45),
    position: 'relative',
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  backButton: {
    width: scale(35),
    height: scale(35),
    borderRadius: scale(20),
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
  },
  RightButton: {
    width: scale(35),
    height: scale(35),
    borderRadius: scale(20),
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
  },
  headerTitle: {
    flex: 1,
    fontFamily: 'Poppins-SemiBold',
    fontSize: typography.fontSize.lg,
    color: colors.black,
    textAlign: 'left',
  },
  leftContainer: {
    width: scale(40),
    height: scale(40),
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartBadgeStyle: {
    position: 'absolute',
    backgroundColor: colors.red,
    borderRadius: metrics.borderRadius.lg,
    height: scale(18),
    maxWidth: scale(24),
    minWidth: scale(18),
    alignItems: 'center',
    justifyContent: 'center',
    top: scale(-5),
    right: scale(-5),
  },
  cartBadgeText: {
    fontSize: typography.fontSize.xxs,
    color: 'white',
  },
});
